-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. Profiles (Extends Supabase Auth)
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  full_name text,
  avatar_url text,
  role text default 'user', -- 'user', 'admin', 'org_admin'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Courses
create table courses (
  id bigint generated by default as identity primary key,
  title text not null,
  author text not null,
  category text not null,
  description text,
  image_url text,
  duration text,
  rating numeric(3, 2) default 0.0,
  badges text[], -- Array of strings: ['REQUIRED', 'SHRM', 'HRCI']
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Modules
create table modules (
  id uuid default uuid_generate_v4() primary key,
  course_id bigint references courses(id) on delete cascade not null,
  title text not null,
  "order" integer not null, -- To maintain sequence
  duration text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Lessons
create table lessons (
  id uuid default uuid_generate_v4() primary key,
  module_id uuid references modules(id) on delete cascade not null,
  title text not null,
  "order" integer not null,
  duration text,
  type text default 'video', -- 'video', 'quiz', 'article'
  video_url text, -- For future Mux integration
  content text, -- For articles or transcripts
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Resources
create table resources (
  id uuid default uuid_generate_v4() primary key,
  course_id bigint references courses(id) on delete cascade not null,
  title text not null,
  type text not null, -- 'PDF', 'DOC', 'LINK'
  url text not null,
  size text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. User Progress (Tracks completion)
create table user_progress (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  course_id bigint references courses(id) on delete cascade not null,
  lesson_id uuid references lessons(id) on delete cascade, -- Optional, if tracking specific lesson
  is_completed boolean default false,
  last_accessed timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, lesson_id) -- Prevent duplicate records for same lesson
);

-- 7. User Collections (Saved Courses)
create table user_collections (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  label text not null,
  color text not null,
  is_custom boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 8. Collection Items (Many-to-Many: Courses <-> Collections)
create table collection_items (
  collection_id uuid references user_collections(id) on delete cascade not null,
  course_id bigint references courses(id) on delete cascade not null,
  added_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (collection_id, course_id)
);

-- RLS Policies (Row Level Security)
alter table profiles enable row level security;
alter table courses enable row level security;
alter table modules enable row level security;
alter table lessons enable row level security;
alter table resources enable row level security;
alter table user_progress enable row level security;
alter table user_collections enable row level security;
alter table collection_items enable row level security;

-- Public Read Access for Courses/Modules/Lessons (Catalog)
create policy "Public courses are viewable by everyone" on courses for select using (true);
create policy "Public modules are viewable by everyone" on modules for select using (true);
create policy "Public lessons are viewable by everyone" on lessons for select using (true);
create policy "Public resources are viewable by everyone" on resources for select using (true);

-- User Specific Policies
create policy "Users can view their own profile" on profiles for select using (auth.uid() = id);
create policy "Users can update their own profile" on profiles for update using (auth.uid() = id);

create policy "Users can view their own progress" on user_progress for select using (auth.uid() = user_id);
create policy "Users can insert their own progress" on user_progress for insert with check (auth.uid() = user_id);
create policy "Users can update their own progress" on user_progress for update using (auth.uid() = user_id);

create policy "Users can view their own collections" on user_collections for select using (auth.uid() = user_id);
create policy "Users can insert their own collections" on user_collections for insert with check (auth.uid() = user_id);
create policy "Users can update their own collections" on user_collections for update using (auth.uid() = user_id);

create policy "Users can view their collection items" on collection_items for select using (
  exists ( select 1 from user_collections where id = collection_items.collection_id and user_id = auth.uid() )
);
create policy "Users can insert collection items" on collection_items for insert with check (
  exists ( select 1 from user_collections where id = collection_items.collection_id and user_id = auth.uid() )
);

-- Trigger to create profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
