-- Create prompt_suggestions table
CREATE TABLE IF NOT EXISTS public.prompt_suggestions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_context text NOT NULL CHECK (page_context IN ('user_dashboard', 'employee_dashboard', 'org_admin_dashboard')),
    label text NOT NULL,
    prompt text NOT NULL,
    category text,
    order_index integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.prompt_suggestions ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Allow read access for all authenticated users" ON public.prompt_suggestions
    FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "Allow write access for admins" ON public.prompt_suggestions
    FOR ALL
    TO authenticated
    USING (
        (SELECT role FROM auth.users WHERE id = auth.uid()) = 'service_role' OR
        (auth.jwt() ->> 'role') = 'service_role' OR
        EXISTS (
            SELECT 1 FROM auth.users 
            WHERE id = auth.uid() 
            AND (raw_user_meta_data->>'role' = 'admin' OR raw_app_meta_data->>'role' = 'admin')
        )
    );

-- Seed Data (User Dashboard)
INSERT INTO public.prompt_suggestions (page_context, label, prompt, category, order_index) VALUES
-- Hero Prompts
('user_dashboard', 'Role-play a difficult conversation', 'I need to have a difficult conversation with an employee who is underperforming. Can you role-play this with me? You act as the employee (defensive but open to feedback), and I will be the manager. Start by asking me for the context of the situation.', 'Communication', 0),
('user_dashboard', 'Draft a policy announcement', 'I need to draft an email announcing a new "Return to Office" policy (3 days a week). The tone should be empathetic but firm, emphasizing collaboration while acknowledging the shift. Please draft 3 variations: one direct, one softer, and one focusing purely on the benefits.', 'Communication', 1),
('user_dashboard', 'Analyze my leadership style', 'I want to analyze my leadership style based on a recent situation. I will describe a scenario and how I handled it, and I want you to critique it using the Situational Leadership II framework. Ready?', 'Leadership', 2),
-- Panel Prompts
('user_dashboard', 'Prepare for a salary negotiation', 'I have an employee asking for a raise that is outside our budget. Help me prepare for this negotiation. What are some non-monetary benefits I can offer, and how should I structure the conversation to maintain their motivation?', 'Leadership', 3),
('user_dashboard', 'Create an onboarding checklist', 'Create a comprehensive onboarding checklist for a new Senior Marketing Manager. Break it down by: Pre-boarding, Day 1, Week 1, Month 1, and Month 3. Focus on cultural integration as much as tactical tasks.', 'Strategy', 4),
('user_dashboard', 'Summarize key HR trends', 'What are the top 5 trends in Human Resources for 2025 regarding AI and automation? Please provide a brief summary of each and one actionable step a mid-sized company can take to prepare.', 'Strategy', 5),
('user_dashboard', 'Write a job description', 'I need a job description for a "People Operations Coordinator". The culture is fast-paced and startup-like. Include responsibilities, required skills, and a "Why you''ll love us" section that highlights autonomy and growth.', 'General', 6),
('user_dashboard', 'Mediate a team conflict', 'Two of my direct reports are in conflict over project ownership. One feels stepped on, the other feels they are just being proactive. Guide me through a mediation process to resolve this and clarify roles.', 'Leadership', 7),
('user_dashboard', 'Design a wellness initiative', 'I want to launch a wellness initiative for a remote-first team. It needs to be low-cost but high-impact. Give me 5 creative ideas that go beyond just "yoga classes".', 'Wellness', 8),
('user_dashboard', 'Explain a complex benefit', 'Explain how an HSA (Health Savings Account) works to a young employee who has never had one. Use simple analogies and bullet points. Focus on the triple tax advantage.', 'Communication', 9),
('user_dashboard', 'Conduct a stay interview', 'I want to conduct stay interviews with my top performers to ensure they are happy. What are the 5 most powerful questions I should ask to uncover their true feelings and retention risks?', 'Leadership', 10),
('user_dashboard', 'Draft a termination script', 'I have to terminate an employee for repeated policy violations (attendance). Please write a script for the meeting. It needs to be professional, direct, and legally sound (standard at-will employment context), minimizing conflict.', 'Communication', 11),
('user_dashboard', 'Brainstorm team building', 'I need 3 unique team-building activity ideas for a hybrid team (some in office, some remote) that actually build trust and aren''t just "forced fun".', 'General', 12);

-- Seed Data (Employee Dashboard - Mocked similar to User for now, but distinct context)
INSERT INTO public.prompt_suggestions (page_context, label, prompt, category, order_index) VALUES
('employee_dashboard', 'How can I improve my skills?', 'I want to improve my skills in my current role. Can you help me identify areas for growth and suggest resources?', 'Growth', 0),
('employee_dashboard', 'Prepare for performance review', 'I have a performance review coming up. Help me summarize my achievements and prepare for potential feedback.', 'Career', 1),
('employee_dashboard', 'Draft a goal setting plan', 'I need to set goals for the next quarter. Help me draft SMART goals that align with my team''s objectives.', 'Productivity', 2);
-- Add default prompts for Org Admin Dashboard
INSERT INTO public.prompt_suggestions (page_context, label, prompt, category, order_index)
VALUES
    ('org_admin_dashboard', 'Analyze Team Progress', 'Analyze the learning progress of my team this month. Who are the top performers, and who needs support?', 'Analytics', 0),
    ('org_admin_dashboard', 'ROI Report', 'Draft a brief report for the executive team summarizing the ROI of our learning program, focusing on certification credits earned and skills acquired.', 'Reporting', 1),
    ('org_admin_dashboard', 'Assign Training', 'Suggest a learning path for a new First-Time Manager based on our available leadership courses.', 'Management', 2),
    ('org_admin_dashboard', 'Skill Gap Analysis', 'Based on the courses my team is taking, what skills are we building, and where might we have gaps?', 'Strategy', 3);
-- Update check constraint to allow instructor_dashboard
ALTER TABLE public.prompt_suggestions DROP CONSTRAINT IF EXISTS prompt_suggestions_page_context_check;

ALTER TABLE public.prompt_suggestions 
ADD CONSTRAINT prompt_suggestions_page_context_check 
CHECK (page_context IN ('user_dashboard', 'employee_dashboard', 'org_admin_dashboard', 'instructor_dashboard'));

-- Add default prompt suggestions for Instructor Dashboard
INSERT INTO public.prompt_suggestions (page_context, label, prompt, category, order_index) VALUES
('instructor_dashboard', 'Analyze my performance', 'Analyze the performance of my courses this month compared to last month.', 'Analytics', 0),
('instructor_dashboard', 'Trending Topics', 'What are the top trending HR topics right now that I should create content about?', 'Inspiration', 1),
('instructor_dashboard', 'Draft Course Outline', 'Help me draft a course outline for a new course on "AI in HR".', 'Content Creation', 2),
('instructor_dashboard', 'Explain Earnings', 'How are my earnings calculated?', 'Financials', 3);
-- 1. Create context_embeddings table
CREATE TABLE IF NOT EXISTS public.context_embeddings (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    item_type text NOT NULL, -- 'COURSE', 'LESSON', 'RESOURCE', 'CONVERSATION', etc.
    item_id text NOT NULL,
    content text NOT NULL,
    embedding vector(768),
    metadata jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index for vector search (IVFFlat for performance, adjust lists based on data size)
-- Note: IVFFlat requires some data to be effective, but we create it now.
-- IF NOT EXISTS is not supported for CREATE INDEX ON ... USING, so we wrap in DO block or just let it fail if exists (but better to be safe)
-- For simplicity in this migration, we'll skip the index creation here or use a safe approach.
-- Supabase/Postgres usually handles index creation fine.
CREATE INDEX IF NOT EXISTS context_embeddings_embedding_idx ON public.context_embeddings USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);


-- 2. Modify collection_items to be polymorphic
-- First, add the new columns
ALTER TABLE public.collection_items
ADD COLUMN IF NOT EXISTS item_type text,
ADD COLUMN IF NOT EXISTS item_id text;

-- Migrate existing data (assuming all current items are courses)
UPDATE public.collection_items
SET item_type = 'COURSE', item_id = course_id::text
WHERE item_type IS NULL;

-- Make new columns not null
ALTER TABLE public.collection_items
ALTER COLUMN item_type SET NOT NULL,
ALTER COLUMN item_id SET NOT NULL;

-- Drop old PK and add new one
ALTER TABLE public.collection_items
DROP CONSTRAINT IF EXISTS collection_items_pkey;

ALTER TABLE public.collection_items
ADD CONSTRAINT collection_items_pkey PRIMARY KEY (collection_id, item_type, item_id);

-- Make course_id nullable (for backward compatibility, we keep it but it's not the PK anymore)
ALTER TABLE public.collection_items
ALTER COLUMN course_id DROP NOT NULL;


-- 3. Seed System Prompts
INSERT INTO public.ai_system_prompts (agent_type, system_instruction)
VALUES
('course_assistant', 'You are the Course Assistant. Your goal is to answer questions specifically about the course content. Use the provided Course Context (Lessons, Resources) to answer. If the answer is not in the course, state that clearly.'),
('course_tutor', 'You are the Course Tutor. Your goal is to provide a personalized learning experience. Do not just answer questions; guide the user with Socratic questioning. Use the User Profile to tailor your teaching style.'),
('platform_assistant', 'You are the Platform Assistant (Prometheus). You have access to the entire library of content. Help the user find courses, answer broad HR questions, and navigate the platform.'),
('collection_assistant', 'You are the Collection Assistant. You are an expert on the specific items in this collection. Synthesize information across the different items (Courses, Lessons, Documents) in this collection.')
ON CONFLICT (agent_type) DO UPDATE
SET system_instruction = EXCLUDED.system_instruction;
-- Seed System Prompts
INSERT INTO ai_system_prompts (agent_type, system_instruction)
VALUES 
    ('platform_assistant', 'You are the Platform Assistant for EnhancedHR. Your goal is to help users navigate the platform, find courses, and answer general HR questions. You have access to the entire library of courses and the user''s profile.'),
    ('collection_assistant', 'You are the Collection Assistant. You are context-aware of the specific collection the user is viewing. Help them synthesize information across the courses in this collection.'),
    ('course_assistant', 'You are the Course Assistant. You are an expert on this specific course. Answer questions based ONLY on the course material provided in the transcript and resources.'),
    ('course_tutor', 'You are the Course Tutor. Your goal is not just to answer, but to teach. Use Socratic methods, ask probing questions, and help the user apply the course concepts to their specific role and company context.')
ON CONFLICT (agent_type) DO NOTHING;
-- Add missing columns to courses table
ALTER TABLE courses ADD COLUMN IF NOT EXISTS is_saved boolean DEFAULT false;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS status text DEFAULT 'draft';
ALTER TABLE courses ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS duration text;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS rating numeric DEFAULT 0;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS badges text[] DEFAULT '{}';
ALTER TABLE courses ADD COLUMN IF NOT EXISTS image_url text;
-- Enable RLS on courses table
ALTER TABLE courses ENABLE ROW LEVEL SECURITY;

-- Create policy to allow everyone to read courses
CREATE POLICY "Enable read access for all users" ON "public"."courses"
AS PERMISSIVE FOR SELECT
TO public
USING (true);

-- Create policy to allow admins to insert/update/delete
CREATE POLICY "Enable write access for admins" ON "public"."courses"
AS PERMISSIVE FOR ALL
TO authenticated
USING ((auth.jwt() ->> 'role') = 'admin' OR (auth.jwt() ->> 'email') LIKE '%admin%')
WITH CHECK ((auth.jwt() ->> 'role') = 'admin' OR (auth.jwt() ->> 'email') LIKE '%admin%');
-- Add collections column to courses table
ALTER TABLE courses ADD COLUMN IF NOT EXISTS collections text[] DEFAULT '{}';

-- Force schema cache reload (by notifying PostgREST if configured, or just by the DDL change)
NOTIFY pgrst, 'reload schema';
-- Seed Courses
INSERT INTO courses (id, title, author, category, image_url, description, duration, rating, badges, is_saved, collections, created_at, status)
VALUES 
  (101, 'AI Leadership Strategies', 'Dr. Sarah Chen', 'AI for HR', 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?q=80&w=1000&auto=format&fit=crop', 'Master the art of leading teams through the AI revolution. Learn to balance automation with human empathy.', '4h 15m', 4.8, ARRAY['REQUIRED', 'SHRM'], true, ARRAY['favorites'], NOW() - INTERVAL '2 days', 'published'),
  (102, 'Generative AI for Recruiters', 'Tech HR Labs', 'AI for HR', 'https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=1000&auto=format&fit=crop', 'Practical applications of LLMs in sourcing, screening, and communicating with candidates.', '3h 00m', 4.8, ARRAY['SHRM'], true, ARRAY['to_learn'], NOW() - INTERVAL '10 days', 'published'),
  (103, 'Prompt Engineering 101', 'Alex Rivera', 'AI for HR', 'https://images.unsplash.com/photo-1678911820864-e2c567c655d7?q=80&w=1000&auto=format&fit=crop', 'Learn the specific syntax and structures to get the best results from ChatGPT and Claude for HR tasks.', '2h 15m', 4.9, ARRAY[]::text[], false, ARRAY[]::text[], NOW() - INTERVAL '1 day', 'published'),
  (104, 'Ethical AI Governance', 'Legal Dept & IT', 'AI for HR', 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=1000&auto=format&fit=crop', 'Understanding bias, privacy, and security when deploying AI tools in the workplace.', '1h 30m', 4.5, ARRAY['REQUIRED'], false, ARRAY[]::text[], NOW() - INTERVAL '45 days', 'published'),
  (105, 'Predictive Retention Models', 'Data Science Team', 'AI for HR', 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1000&auto=format&fit=crop', 'Using machine learning to identify flight risks before they hand in their resignation.', '5h 00m', 4.7, ARRAY['HRCI'], true, ARRAY['research'], NOW() - INTERVAL '5 days', 'published'),
  (106, 'The Automated Onboarding', 'People Ops', 'AI for HR', 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?q=80&w=1000&auto=format&fit=crop', 'Building a seamless, AI-assisted onboarding journey that feels personal at scale.', '3h 45m', 4.2, ARRAY[]::text[], false, ARRAY[]::text[], NOW() - INTERVAL '100 days', 'draft'),
  (201, 'Change Management Essentials', 'Robert Fox', 'Leadership', 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=1000&auto=format&fit=crop', 'Navigating organizational transitions with minimal disruption and maximum employee engagement.', '5h 15m', 4.6, ARRAY['HRCI'], true, ARRAY['to_learn'], NOW() - INTERVAL '20 days', 'published'),
  (202, 'Leading Remote Teams', 'Sarah Jenks', 'Leadership', 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=1000&auto=format&fit=crop', 'Strategies for maintaining culture, productivity, and connection in a distributed workforce.', '3h 20m', 4.5, ARRAY[]::text[], false, ARRAY[]::text[], NOW(), 'published'),
  (203, 'Executive Presence', 'Marcus Aurelius II', 'Leadership', 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=1000&auto=format&fit=crop', 'How to command a room, speak with authority, and influence C-Suite stakeholders.', '4h 00m', 4.9, ARRAY['SHRM'], true, ARRAY['favorites'], NOW() - INTERVAL '8 days', 'published'),
  (204, 'Strategic Visioning', 'Board of Directors', 'Leadership', 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=1000&auto=format&fit=crop', 'Moving from tactical execution to long-term strategic planning.', '6h 30m', 4.7, ARRAY['REQUIRED'], false, ARRAY[]::text[], NOW() - INTERVAL '300 days', 'published'),
  (205, 'Mentorship Masterclass', 'Elena Fisher', 'Leadership', 'https://images.unsplash.com/photo-1531482615713-2afd69097998?q=80&w=1000&auto=format&fit=crop', 'How to effectively mentor junior talent and build the next generation of leaders.', '2h 45m', 4.8, ARRAY[]::text[], true, ARRAY['research'], NOW() - INTERVAL '15 days', 'published'),
  (206, 'Conflict Resolution', 'HR Mediation Team', 'Leadership', 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=1000&auto=format&fit=crop', 'Turning workplace conflict into constructive dialogue and growth opportunities.', '3h 15m', 4.6, ARRAY['HRCI'], false, ARRAY[]::text[], NOW() - INTERVAL '60 days', 'draft'),
  (301, 'Strategic HR Management', 'James Wilson', 'Business Functions', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1000&auto=format&fit=crop', 'Aligning human resources with the core business objectives to drive long-term organizational success.', '8h 45m', 4.2, ARRAY['REQUIRED'], false, ARRAY[]::text[], NOW() - INTERVAL '200 days', 'published'),
  (302, 'Compensation & Benefits', 'Finance Dept', 'Business Functions', 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?q=80&w=1000&auto=format&fit=crop', 'Designing competitive packages that attract talent without breaking the bank.', '5h 30m', 4.4, ARRAY['SHRM'], true, ARRAY['research'], NOW() - INTERVAL '4 days', 'published'),
  (303, 'The Future of HR Analytics', 'Elena Fisher', 'Business Functions', 'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?q=80&w=1000&auto=format&fit=crop', 'Dive deep into predictive analytics and how data is shaping the future of talent acquisition.', '6h 00m', 4.9, ARRAY['SHRM', 'HRCI'], true, ARRAY['to_learn'], NOW() - INTERVAL '1 day', 'published'),
  (304, 'Labor Law Compliance', 'Legal Partners LLP', 'Business Functions', 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?q=80&w=1000&auto=format&fit=crop', 'An essential update on federal and state labor laws for the current fiscal year.', '4h 00m', 4.3, ARRAY['REQUIRED', 'HRCI'], false, ARRAY[]::text[], NOW() - INTERVAL '180 days', 'published'),
  (305, 'Agile HR Workflows', 'Scrum Masters', 'Business Functions', 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?q=80&w=1000&auto=format&fit=crop', 'Implementing agile methodologies within the People Operations function.', '3h 15m', 4.6, ARRAY[]::text[], false, ARRAY[]::text[], NOW() - INTERVAL '25 days', 'draft'),
  (306, 'Global Mobility', 'International Team', 'Business Functions', 'https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?q=80&w=1000&auto=format&fit=crop', 'Managing expatriate assignments, visas, and cross-border taxation issues.', '4h 45m', 4.5, ARRAY[]::text[], false, ARRAY[]::text[], NOW() - INTERVAL '40 days', 'published'),
  (401, 'Crisis Communication', 'Marcus Rodriguez', 'Soft Skills', 'https://images.unsplash.com/photo-1557426272-fc759fdf7a8d?q=80&w=1000&auto=format&fit=crop', 'Effective frameworks for handling internal and external communications during organizational crises.', '2h 30m', 4.5, ARRAY['HRCI'], false, ARRAY[]::text[], NOW() - INTERVAL '3 days', 'published'),
  (402, 'Active Listening Lab', 'Dr. Lisa Su', 'Soft Skills', 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=1000&auto=format&fit=crop', 'Techniques to truly hear what your employees are saying, not just what they are speaking.', '1h 45m', 4.8, ARRAY[]::text[], true, ARRAY['favorites'], NOW() - INTERVAL '7 days', 'published'),
  (403, 'Negotiation Tactics', 'The Dealmakers', 'Soft Skills', 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?q=80&w=1000&auto=format&fit=crop', 'Getting to ''Yes'' in salary negotiations, vendor contracts, and internal disputes.', '3h 00m', 4.7, ARRAY['SHRM'], false, ARRAY[]::text[], NOW() - INTERVAL '90 days', 'published'),
  (404, 'Emotional Intelligence', 'Daniel Goleman (Guest)', 'Soft Skills', 'https://images.unsplash.com/photo-1493612276216-ee3925520721?q=80&w=1000&auto=format&fit=crop', 'Understanding your own emotions and those of others to manage relationships effectively.', '4h 15m', 4.9, ARRAY['REQUIRED'], true, ARRAY['to_learn'], NOW() - INTERVAL '12 days', 'published'),
  (405, 'Time Management', 'Productivity Pros', 'Soft Skills', 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?q=80&w=1000&auto=format&fit=crop', 'Deep work, time blocking, and the art of saying no to non-essential meetings.', '2h 00m', 4.4, ARRAY[]::text[], false, ARRAY[]::text[], NOW() - INTERVAL '30 days', 'published'),
  (406, 'Public Speaking', 'Toastmasters', 'Soft Skills', 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?q=80&w=1000&auto=format&fit=crop', 'Overcome stage fright and deliver compelling presentations to large groups.', '3h 30m', 4.6, ARRAY[]::text[], false, ARRAY[]::text[], NOW() - INTERVAL '55 days', 'published'),
  (501, 'Diversity & Inclusion Stories', 'Maya Patel', 'HR Stories', 'https://images.unsplash.com/photo-1573164713988-8665fc963095?q=80&w=1000&auto=format&fit=crop', 'Real-world stories of building inclusive workplace cultures that foster innovation and belonging.', '3h 30m', 4.7, ARRAY['SHRM'], false, ARRAY[]::text[], NOW() - INTERVAL '2 days', 'published'),
  (502, 'Startup to IPO: A Journey', 'Founders Collective', 'HR Stories', 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=1000&auto=format&fit=crop', 'The chaotic, exciting, and difficult HR challenges faced during rapid scaling.', '2h 00m', 4.8, ARRAY[]::text[], true, ARRAY['research'], NOW() - INTERVAL '18 days', 'published'),
  (503, 'The 4-Day Work Week', 'Case Study Group', 'HR Stories', 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?q=80&w=1000&auto=format&fit=crop', 'Interviews with companies that successfully made the switch, and those that failed.', '1h 45m', 4.5, ARRAY[]::text[], false, ARRAY[]::text[], NOW(), 'published'),
  (504, 'From Toxic to Thriving', 'Culture Turnaround', 'HR Stories', 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?q=80&w=1000&auto=format&fit=crop', 'A documentary-style look at how one company completely overhauled its toxic culture.', '2h 30m', 4.9, ARRAY['SHRM'], true, ARRAY['favorites'], NOW() - INTERVAL '6 days', 'published'),
  (505, 'Lessons from the Factory Floor', 'Manufacturing HR', 'HR Stories', 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?q=80&w=1000&auto=format&fit=crop', 'Unique HR challenges in the manufacturing sector and what corporate can learn from them.', '2h 15m', 4.4, ARRAY[]::text[], false, ARRAY[]::text[], NOW() - INTERVAL '365 days', 'published'),
  (601, 'Radical Candor Review', 'Book Club Group', 'Book Club', 'https://images.unsplash.com/photo-1491841550275-ad7854e35ca6?q=80&w=1000&auto=format&fit=crop', 'A deep dive group discussion into Kim Scott''s Radical Candor and its application in modern HR.', '1h 30m', 4.9, ARRAY[]::text[], false, ARRAY[]::text[], NOW() - INTERVAL '14 days', 'published'),
  (602, 'Good to Great', 'Jim Collins (Analysis)', 'Book Club', 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?q=80&w=1000&auto=format&fit=crop', 'Breaking down the seminal text on why some companies make the leap and others don''t.', '2h 00m', 4.8, ARRAY[]::text[], true, ARRAY['research'], NOW() - INTERVAL '500 days', 'published'),
  (603, 'Work Rules!', 'Google HR Alumni', 'Book Club', 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?q=80&w=1000&auto=format&fit=crop', 'Discussing Laszlo Bock''s insights from inside Google to transform how you live and lead.', '1h 45m', 4.7, ARRAY[]::text[], false, ARRAY[]::text[], NOW() - INTERVAL '400 days', 'published'),
  (604, 'Dare to Lead', 'Brené Brown Fan Club', 'Book Club', 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=1000&auto=format&fit=crop', 'Exploring courage, vulnerability, and values in the workplace context.', '2h 15m', 4.9, ARRAY['SHRM'], true, ARRAY['favorites'], NOW() - INTERVAL '22 days', 'published'),
  (605, 'The Culture Map', 'Erin Meyer Discussion', 'Book Club', 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?q=80&w=1000&auto=format&fit=crop', 'Breaking through the invisible boundaries of global business.', '1h 50m', 4.6, ARRAY[]::text[], false, ARRAY[]::text[], NOW() - INTERVAL '28 days', 'published')
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  author = EXCLUDED.author,
  category = EXCLUDED.category,
  image_url = EXCLUDED.image_url,
  description = EXCLUDED.description,
  duration = EXCLUDED.duration,
  rating = EXCLUDED.rating,
  badges = EXCLUDED.badges,
  is_saved = EXCLUDED.is_saved,
  collections = EXCLUDED.collections,
  status = EXCLUDED.status;
-- Set Admin Role for User
-- Replace 'rustylindquist@gmail.com' with the actual user email if different

-- 1. Update public.profiles
UPDATE public.profiles
SET role = 'admin'
WHERE id IN (
  SELECT id FROM auth.users WHERE email = 'rustylindquist@gmail.com'
);

-- 2. Update auth.users metadata (so session has correct role on next login)
UPDATE auth.users
SET raw_user_meta_data = jsonb_set(
  COALESCE(raw_user_meta_data, '{}'::jsonb),
  '{role}',
  '"admin"'
)
WHERE email = 'rustylindquist@gmail.com';
