-- Create prompt_suggestions table
CREATE TABLE IF NOT EXISTS public.prompt_suggestions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_context text NOT NULL CHECK (page_context IN ('user_dashboard', 'employee_dashboard', 'org_admin_dashboard')),
    label text NOT NULL,
    prompt text NOT NULL,
    category text,
    order_index integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.prompt_suggestions ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Allow read access for all authenticated users" ON public.prompt_suggestions
    FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "Allow write access for admins" ON public.prompt_suggestions
    FOR ALL
    TO authenticated
    USING (
        (SELECT role FROM auth.users WHERE id = auth.uid()) = 'service_role' OR
        (auth.jwt() ->> 'role') = 'service_role' OR
        EXISTS (
            SELECT 1 FROM auth.users 
            WHERE id = auth.uid() 
            AND (raw_user_meta_data->>'role' = 'admin' OR raw_app_meta_data->>'role' = 'admin')
        )
    );

-- Seed Data (User Dashboard)
INSERT INTO public.prompt_suggestions (page_context, label, prompt, category, order_index) VALUES
-- Hero Prompts
('user_dashboard', 'Role-play a difficult conversation', 'I need to have a difficult conversation with an employee who is underperforming. Can you role-play this with me? You act as the employee (defensive but open to feedback), and I will be the manager. Start by asking me for the context of the situation.', 'Communication', 0),
('user_dashboard', 'Draft a policy announcement', 'I need to draft an email announcing a new "Return to Office" policy (3 days a week). The tone should be empathetic but firm, emphasizing collaboration while acknowledging the shift. Please draft 3 variations: one direct, one softer, and one focusing purely on the benefits.', 'Communication', 1),
('user_dashboard', 'Analyze my leadership style', 'I want to analyze my leadership style based on a recent situation. I will describe a scenario and how I handled it, and I want you to critique it using the Situational Leadership II framework. Ready?', 'Leadership', 2),
-- Panel Prompts
('user_dashboard', 'Prepare for a salary negotiation', 'I have an employee asking for a raise that is outside our budget. Help me prepare for this negotiation. What are some non-monetary benefits I can offer, and how should I structure the conversation to maintain their motivation?', 'Leadership', 3),
('user_dashboard', 'Create an onboarding checklist', 'Create a comprehensive onboarding checklist for a new Senior Marketing Manager. Break it down by: Pre-boarding, Day 1, Week 1, Month 1, and Month 3. Focus on cultural integration as much as tactical tasks.', 'Strategy', 4),
('user_dashboard', 'Summarize key HR trends', 'What are the top 5 trends in Human Resources for 2025 regarding AI and automation? Please provide a brief summary of each and one actionable step a mid-sized company can take to prepare.', 'Strategy', 5),
('user_dashboard', 'Write a job description', 'I need a job description for a "People Operations Coordinator". The culture is fast-paced and startup-like. Include responsibilities, required skills, and a "Why you''ll love us" section that highlights autonomy and growth.', 'General', 6),
('user_dashboard', 'Mediate a team conflict', 'Two of my direct reports are in conflict over project ownership. One feels stepped on, the other feels they are just being proactive. Guide me through a mediation process to resolve this and clarify roles.', 'Leadership', 7),
('user_dashboard', 'Design a wellness initiative', 'I want to launch a wellness initiative for a remote-first team. It needs to be low-cost but high-impact. Give me 5 creative ideas that go beyond just "yoga classes".', 'Wellness', 8),
('user_dashboard', 'Explain a complex benefit', 'Explain how an HSA (Health Savings Account) works to a young employee who has never had one. Use simple analogies and bullet points. Focus on the triple tax advantage.', 'Communication', 9),
('user_dashboard', 'Conduct a stay interview', 'I want to conduct stay interviews with my top performers to ensure they are happy. What are the 5 most powerful questions I should ask to uncover their true feelings and retention risks?', 'Leadership', 10),
('user_dashboard', 'Draft a termination script', 'I have to terminate an employee for repeated policy violations (attendance). Please write a script for the meeting. It needs to be professional, direct, and legally sound (standard at-will employment context), minimizing conflict.', 'Communication', 11),
('user_dashboard', 'Brainstorm team building', 'I need 3 unique team-building activity ideas for a hybrid team (some in office, some remote) that actually build trust and aren''t just "forced fun".', 'General', 12);

-- Seed Data (Employee Dashboard - Mocked similar to User for now, but distinct context)
INSERT INTO public.prompt_suggestions (page_context, label, prompt, category, order_index) VALUES
('employee_dashboard', 'How can I improve my skills?', 'I want to improve my skills in my current role. Can you help me identify areas for growth and suggest resources?', 'Growth', 0),
('employee_dashboard', 'Prepare for performance review', 'I have a performance review coming up. Help me summarize my achievements and prepare for potential feedback.', 'Career', 1),
('employee_dashboard', 'Draft a goal setting plan', 'I need to set goals for the next quarter. Help me draft SMART goals that align with my team''s objectives.', 'Productivity', 2);
